### PR TITLE
feat: generics support

### PR DESCRIPTION
**Pull request by ilteoood**
Enable generics support in a non-breaking way, to support additional properties that can be injected from qiankun

### CODE REVIEW

**Comment by tengmaoqing** [comment]
Thanks for your PR.

In my opinion, we can do this through  `declare module`.

env.d.ts
```javascript
import 'vite-plugin-qiankun/dist/helper'

declare module 'vite-plugin-qiankun/dist/helper' {
  interface QiankunProps {
    test: string
  }
}
```

main.ts 

import {QiankunProps} from  'vite-plugin-qiankun/dist/helper'

```javascript
const a: QiankunProps = {
  container: document.querySelector("#root") as HTMLElement,
  test: 'sss',
};

```

So, maybe you can provide a specific scene.

**Comment by ilteoood** [comment]
Hi @tengmaoqing, sorry for the delay.

Unfortunately your example isn't valid for my use case: one of the properties that I'm trying to introduce is a ReplaySubject, which supports the Generics.

As `QiankunProps` is not generic, I can't use your suggestion because all its declarations must have identical type parameters.

**Comment by ilteoood** [comment]
Optionally, I could copy-paste the same code in every template that I created, but I would really prefer to centralize as much as possible.

**Comment by tengmaoqing** [comment]
@ilteoood .Sorry, I've been a little busy lately.
 In fact, This is a breaking change. It conflicts with here #22 .

**Comment by tengmaoqing** [comment]
Maybe we should come up with a better way to solve this issue. `type` vs `interface`

**Pull request closed without merging**
